import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/website/shared/navbar";
import Footer from "@/components/website/shared/footer";
import TopHeader from "@/components/website/shared/TopHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <TopHeader />
      <Navbar /> {children} <Footer />
    </>
  );
}
