import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/website/shared/navbar";
import Footer from "@/components/website/shared/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
       {children} 
    </div>
  );
}
