import type { Metadata } from "next";
import "../globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex items-center justify-center gap-6">
      <Image
        src={"/asset/auth-diving.jpg"}
        width={1024}
        height={1024}
        alt="Man Diving"
        className="flex-1"
      />
      <div className="flex-1">{children}</div>
    </div>
  );
}
