import type { Metadata } from "next";
import "../globals.css";
import AccountSidebar from "@/components/account/account-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <AccountSidebar />
      <div>{children}</div>
    </div>
  );
}
